insert into countries (name, code) values ('Alaska','1907');
insert into countries (name, code) values ('Argelia','213');
insert into countries (name, code) values ('Albania','355');
insert into countries (name, code) values ('Argentina','54');
insert into countries (name, code) values ('Alemania','49');
insert into countries (name, code) values ('Armenia','374');
insert into countries (name, code) values ('Andorra','376');
insert into countries (name, code) values ('Australia','61');
insert into countries (name, code) values ('Angola','244');
insert into countries (name, code) values ('Austria','43');
insert into countries (name, code) values ('Arabia Saudí','966');
insert into countries (name, code) values ('Bahreim','973');
insert into countries (name, code) values ('Bosnia','387');
insert into countries (name, code) values ('Bangladesh','880');
insert into countries (name, code) values ('Brasil','55');
insert into countries (name, code) values ('Bélgica','32');
insert into countries (name, code) values ('Bulgaria','359');
insert into countries (name, code) values ('Bolivia','591');
insert into countries (name, code) values ('Cabo Verde','238');
insert into countries (name, code) values ('Colombia','57');
insert into countries (name, code) values ('Camboya','855');
insert into countries (name, code) values ('Congo, Rep.','242');
insert into countries (name, code) values ('Camerún','237');
insert into countries (name, code) values ('Congo, Rep. Democ.','243');
insert into countries (name, code) values ('Canadá','1');
insert into countries (name, code) values ('Corea, Rep. Democ.','850');
insert into countries (name, code) values ('Centroafricana, Rep.','236');
insert into countries (name, code) values ('Corea, Rep.','82');
insert into countries (name, code) values ('Checa, Rep.','420');
insert into countries (name, code) values ('Costa de Marfil','225');
insert into countries (name, code) values ('Chile','56');
insert into countries (name, code) values ('Costa Rica','506');
insert into countries (name, code) values ('China','86');
insert into countries (name, code) values ('Croacia','385');
insert into countries (name, code) values ('Chipre','357');
insert into countries (name, code) values ('Cuba','53');
insert into countries (name, code) values ('Dinamarca','45');
insert into countries (name, code) values ('Dominicana, Rep.','1809');
insert into countries (name, code) values ('Ecuador','593');
insert into countries (name, code) values ('Eslovenia','386');
insert into countries (name, code) values ('Egipto','20');
insert into countries (name, code) values ('España','34');
insert into countries (name, code) values ('El Salvador','503');
insert into countries (name, code) values ('Estados Unidos','1');
insert into countries (name, code) values ('Emiratos Árabes Unidos','971');
insert into countries (name, code) values ('Estonia','372');
insert into countries (name, code) values ('Eslovaca, Rep.','421');
insert into countries (name, code) values ('Etiopía','251');
insert into countries (name, code) values ('Filipinas','63');
insert into countries (name, code) values ('Francia','33');
insert into countries (name, code) values ('Finlandia','358');
insert into countries (name, code) values ('Gibraltar','9567');
insert into countries (name, code) values ('Guatemala','502');
insert into countries (name, code) values ('Grecia','30');
insert into countries (name, code) values ('Guinea Ecuatorial','240');
insert into countries (name, code) values ('Groenlandia','299');
insert into countries (name, code) values ('Haití','509');
insert into countries (name, code) values ('Hong Kong','852');
insert into countries (name, code) values ('Hawai','1808');
insert into countries (name, code) values ('Hungría','36');
insert into countries (name, code) values ('Honduras','504');
insert into countries (name, code) values ('India','91');
insert into countries (name, code) values ('Irlanda','353');
insert into countries (name, code) values ('Indonesia','62');
insert into countries (name, code) values ('Islandia','354');
insert into countries (name, code) values ('Irán','98');
insert into countries (name, code) values ('Israel','972');
insert into countries (name, code) values ('Irak','964');
insert into countries (name, code) values ('Italia','39');
insert into countries (name, code) values ('Jamaica','1876');
insert into countries (name, code) values ('Jordania','962');
insert into countries (name, code) values ('Japón','81');
insert into countries (name, code) values ('Kenia ','254');
insert into countries (name, code) values ('Kuwait','965');
insert into countries (name, code) values ('Laos','856');
insert into countries (name, code) values ('Libia','218');
insert into countries (name, code) values ('Letonia','371');
insert into countries (name, code) values ('Liechtenstein','41');
insert into countries (name, code) values ('Líbano','961');
insert into countries (name, code) values ('Lituania','370');
insert into countries (name, code) values ('Liberia','231');
insert into countries (name, code) values ('Luxemburgo','352');
insert into countries (name, code) values ('Madagascar','261');	
insert into countries (name, code) values ('México','52');
insert into countries (name, code) values ('Malasia','60');	
insert into countries (name, code) values ('Moldavia','373');
insert into countries (name, code) values ('Malta','356');	
insert into countries (name, code) values ('Mónaco','377');
insert into countries (name, code) values ('Marruecos','212');	
insert into countries (name, code) values ('Mongolia','976');
insert into countries (name, code) values ('Martinica','596');	
insert into countries (name, code) values ('Mozambique','258');
insert into countries (name, code) values ('Mauritania','222');	 	 
insert into countries (name, code) values ('Namibia','264');	
insert into countries (name, code) values ('Nigeria','234');
insert into countries (name, code) values ('Nepal','977');	
insert into countries (name, code) values ('Noruega','47');
insert into countries (name, code) values ('Nicaragua','505');
insert into countries (name, code) values ('Nueva Zelanda','64');
insert into countries (name, code) values ('Países Bajos','31');
insert into countries (name, code) values ('Perú','51');
insert into countries (name, code) values ('Pakistán','92');	
insert into countries (name, code) values ('Polonia','48');
insert into countries (name, code) values ('Panamá','507');	
insert into countries (name, code) values ('Portugal','351');
insert into countries (name, code) values ('Paraguay','595');
insert into countries (name, code) values ('Puerto Rico','1787');
insert into countries (name, code) values ('Qatar','974'); 
insert into countries (name, code) values ('Reino Unido','44');
insert into countries (name, code) values ('Rusia','7');
insert into countries (name, code) values ('Rumania','40');	 	 
insert into countries (name, code) values ('San Marino','378');
insert into countries (name, code) values ('Sri-Lanka','94');
insert into countries (name, code) values ('Senegal','221');	
insert into countries (name, code) values ('Sudáfrica','27');
insert into countries (name, code) values ('Singapur','65');
insert into countries (name, code) values ('Sudán','249');
insert into countries (name, code) values ('Siria','963');
insert into countries (name, code) values ('Suecia','46');
insert into countries (name, code) values ('Somalia','252');
insert into countries (name, code) values ('Suiza','41');
insert into countries (name, code) values ('Tailandia','66');
insert into countries (name, code) values ('Túnez','216');
insert into countries (name, code) values ('Taiwan','886');	
insert into countries (name, code) values ('Turquía','90');
insert into countries (name, code) values ('Tanzania','255');	 	 
insert into countries (name, code) values ('Ucrania','380');	
insert into countries (name, code) values ('Uruguay','598');
insert into countries (name, code) values ('Uganda','256');	 	 
insert into countries (name, code) values ('Vaticano','39');
insert into countries (name, code) values ('Vietnam','84');
insert into countries (name, code) values ('Venezuela','58');	 	 
insert into countries (name, code) values ('Yemen','967');	
insert into countries (name, code) values ('Yugoslavia','381');
insert into countries (name, code) values ('Zambia','260');	
insert into countries (name, code) values ('Zimbawe','263');


select * from countries
